// Auto-generated file - do not edit manually
// This file will be regenerated by the build process
// Generated on: 2025-09-17T00:00:00.000Z

import { HackathonSummary } from './types';

export const hackathonSummaries: HackathonSummary[] = [
  {
    slug: 'ai-agent-hackathon-2025',
    name: 'AI Agent Hackathon',
    cover: 'https://cdn.andka.my.id/imphnen/534798944_122241336080178516_4647521272813012181_n.jpg',
    description: 'Hackathon dalam rangka AI Agent Kemerdekaan Indonesia. Selama satu minggu, para peserta akan diminta untuk membuat proyek mereka sendiri secara online dengan bantuan lunos.tech, mailry.co, dan unli.dev.',
    prize: 'Rp. 5.000.000',
    tags: ['AI Agent'],
    theme: 'AI Agent untuk Kemerdekaan Indonesia',
    status: 'ended',
    partnersCount: 2,
    submissionsCount: 22,
    submissionWindow: {
      start: '2025-08-15T00:00:00.000Z',
      end: '2025-09-20T23:59:59.999Z'
    }
  }
];

export const hackathonSlugs = ['ai-agent-hackathon-2025'];

export function getHackathonSummaryBySlug(slug: string): HackathonSummary | undefined {
  return hackathonSummaries.find(h => h.slug === slug);
}

export function getActiveHackathons(): HackathonSummary[] {
  return hackathonSummaries.filter(h => h.status === 'active');
}

export function getUpcomingHackathons(): HackathonSummary[] {
  return hackathonSummaries.filter(h => h.status === 'upcoming');
}

export function getFeaturedHackathons(): HackathonSummary[] {
  return hackathonSummaries.filter(h => (h as Record<string, unknown>).featured === true);
}

export function getEndedHackathons(): HackathonSummary[] {
  return hackathonSummaries.filter(h => h.status === 'ended');
}