version: '3.8'
services:
  dimentorin:
    build:
      context: .
      dockerfile: docker/dimentorin.Dockerfile
    ports:
      - "3002:80"
    restart: unless-stopped
    container_name: dimentorin
