import { FC, useState, useEffect, useMemo, useRef } from 'react';
import { Button } from '@imphnen-frontend-service/ui/atoms';
import { cn } from '@imphnen-frontend-service/utils';
import TeamBannerPlaceholder from './team-banner-placeholder';
import { CityFilterSelect } from '../../../../components/city-filter-select';
import {
  TeamOutlined,
  CalendarOutlined,
  SaveOutlined,
  CloseOutlined,
  ExclamationOutlined,
  UserOutlined,
  DeleteOutlined,
  EyeOutlined,
  EyeInvisibleOutlined,
  CrownOutlined,
  CheckCircleOutlined,
  ClockCircleOutlined,
  CloseCircleOutlined,
  CameraOutlined,
  UploadOutlined,
} from '@ant-design/icons';

interface TeamMember {
  id: string;
  joined_at: string;
  role: 'leader' | 'member';
  status: 'pending' | 'accepted' | 'rejected';
  team_id: string;
  user: {
    avatar?: string;
    bio?: string;
    created_at: string;
    email: string;
    fullname: string;
    id: string;
    is_active: boolean;
    location: string;
    phone_number?: string;
    skills: string[];
    updated_at: string;
  };
  user_id: string;
}

interface TeamType {
  id: string;
  name: string;
  description?: string;
  city: string;
  banner?: string;
  logo?: string;
  visibility: 'public' | 'private';
  member_count: number;
  has_submission: boolean;
  created_at: string;
  updated_at: string;
  leader_id: string;
  members: TeamMember[];
}

interface ModalProps {
  isOpen: boolean;
  onClose: () => void;
  team: TeamType | null;
}

const ModalTeamDetail: FC<ModalProps> = ({ isOpen, onClose, team }) => {
  const [formData, setFormData] = useState<TeamType | null>(null);
  const [showDeleteConfirm, setShowDeleteConfirm] = useState(false);
  const [activeTab, setActiveTab] = useState<'details' | 'members'>('details');
  const [showLogoMenu, setShowLogoMenu] = useState(false);
  const logoInputRef = useRef<HTMLInputElement>(null);
  const bannerInputRef = useRef<HTMLInputElement>(null);

  // Initialize form data when modal opens
  useEffect(() => {
    if (isOpen) {
      if (team) {
        // Edit existing team
        setFormData({ ...team });
      } else {
        // Create new team
        setFormData({
          id: '', // Will be generated by backend
          name: '',
          description: '',
          city: '',
          banner: undefined,
          logo: undefined,
          visibility: 'public',
          member_count: 1,
          has_submission: false,
          created_at: new Date().toISOString(),
          updated_at: new Date().toISOString(),
          leader_id: '',
          members: [],
        });
      }
    }
  }, [isOpen, team]);

  // Check if form has changes
  const hasChanges = useMemo(() => {
    if (!formData) return false;
    if (!team) return true; // New team always has changes
    return (
      formData.name !== team.name ||
      formData.description !== team.description ||
      formData.city !== team.city ||
      formData.visibility !== team.visibility ||
      formData.logo !== team.logo ||
      formData.banner !== team.banner
    );
  }, [formData, team]);

  // Check if required fields are filled
  const isFormValid = useMemo(() => {
    if (!formData) return false;
    return formData.name.trim() !== '' && formData.city.trim() !== '';
  }, [formData]);

  const canSave = hasChanges && isFormValid;

  // Get leader and other members
  const leader = team?.members.find((m) => m.role === 'leader');
  const acceptedMembers =
    team?.members.filter((m) => m.status === 'accepted') || [];
  const pendingMembers =
    team?.members.filter((m) => m.status === 'pending') || [];

  if (!isOpen || !formData) return null;

  const handleInputChange = (
    field: keyof TeamType,
    value: string | boolean | 'public' | 'private' | undefined
  ) => {
    setFormData((prev) => (prev ? { ...prev, [field]: value } : null));
  };

  const handleSave = () => {
    if (!formData) return;

    console.log('Saving team:', formData);
    onClose();
  };

  const handleDelete = () => {
    if (!team) return;

    console.log('Deleting team:', team.id);
    setShowDeleteConfirm(false);
    onClose();
  };

  const handleLogoUpload = (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (file) {
      if (!file.type.startsWith('image/')) {
        alert('Please select an image file');
        return;
      }
      if (file.size > 5 * 1024 * 1024) {
        alert('Image size must be less than 5MB');
        return;
      }
      const reader = new FileReader();
      reader.onload = (e) => {
        const logoUrl = e.target?.result as string;
        handleInputChange('logo', logoUrl);
        setShowLogoMenu(false);
      };
      reader.readAsDataURL(file);
    }
  };

  const handleBannerUpload = (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (file) {
      if (!file.type.startsWith('image/')) {
        alert('Please select an image file');
        return;
      }
      if (file.size > 5 * 1024 * 1024) {
        alert('Image size must be less than 5MB');
        return;
      }
      const reader = new FileReader();
      reader.onload = (e) => {
        const bannerUrl = e.target?.result as string;
        handleInputChange('banner', bannerUrl);
      };
      reader.readAsDataURL(file);
    }
  };

  const handleRemoveLogo = () => {
    handleInputChange('logo', undefined);
    setShowLogoMenu(false);
  };

  const handleRemoveBanner = () => {
    handleInputChange('banner', undefined);
  };

  const triggerLogoUpload = () => {
    logoInputRef.current?.click();
  };

  return (
    <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4">
      <div className="bg-white rounded-lg shadow-xl w-full max-w-4xl max-h-[90vh] overflow-y-auto">
        {/* Header */}
        <div className="flex items-center justify-between p-6 border-b border-neutral-200">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-full bg-primary-100 flex items-center justify-center">
              <TeamOutlined className="text-primary-600 text-lg" />
            </div>
            <div>
              <h2 className="text-xl font-semibold text-neutral-900">
                {team ? 'Team Details' : 'Create New Team'}
              </h2>
              <p className="text-sm text-neutral-500">
                {team
                  ? 'View and manage team information'
                  : 'Add a new team to the hackathon'}
              </p>
            </div>
          </div>
          <button
            className="p-2 hover:bg-neutral-100 rounded-lg transition-colors cursor-pointer"
            onClick={() => {
              setShowLogoMenu(false);
              onClose();
            }}
          >
            <CloseOutlined className="text-neutral-400 text-lg" />
          </button>
        </div>

        {/* Content */}
        <div className="p-6 space-y-6" onClick={() => setShowLogoMenu(false)}>
          {/* Hidden File Inputs */}
          <input
            type="file"
            ref={logoInputRef}
            onChange={handleLogoUpload}
            accept="image/*"
            className="hidden"
          />
          <input
            type="file"
            ref={bannerInputRef}
            onChange={handleBannerUpload}
            accept="image/*"
            className="hidden"
          />

          {/* Interactive Banner Section */}
          <div className="space-y-2">
            <label className="block text-sm font-medium text-neutral-700">
              Team Banner
              <span className="text-xs text-neutral-500 ml-2">
                (3:1 aspect ratio recommended)
              </span>
            </label>
            <div className="relative group">
              <TeamBannerPlaceholder
                banner={formData.banner}
                teamName={formData.name || 'Team Name'}
                className="rounded-lg border border-neutral-200 transition-all group-hover:border-primary-300"
              />
              {/* Banner Action Buttons */}
              <div className="absolute inset-0 bg-black/40 rounded-lg opacity-0 group-hover:opacity-100 transition-opacity flex items-center justify-center gap-3">
                <Button
                  variant="primary"
                  size="sm"
                  onClick={(e) => {
                    e.stopPropagation();
                    bannerInputRef.current?.click();
                  }}
                  className="bg-white/90 hover:bg-white text-neutral-700 border-transparent shadow-sm gap-2"
                >
                  <UploadOutlined className="text-sm" />
                  {formData.banner ? 'Change Banner' : 'Add Banner'}
                </Button>
                {formData.banner && (
                  <Button
                    variant="secondary"
                    size="sm"
                    onClick={(e) => {
                      e.stopPropagation();
                      handleRemoveBanner();
                    }}
                    className="bg-white/90 hover:bg-white text-red-600 border-transparent shadow-sm hover:text-red-700 gap-2"
                  >
                    <DeleteOutlined className="text-sm" />
                    Delete Banner
                  </Button>
                )}
              </div>
            </div>
          </div>

          {/* Team Logo & Name Row */}
          <div className="grid grid-cols-12 gap-4 items-start">
            {/* Interactive Team Logo */}
            <div className="col-span-2">
              <label className="block text-sm font-medium text-neutral-700 mb-2">
                Logo
              </label>
              <div className="relative group">
                <div className="w-24 h-24 rounded-full bg-neutral-100 flex items-center justify-center overflow-hidden border border-neutral-200 group-hover:border-primary-300 transition-colors">
                  {formData.logo ? (
                    <img
                      src={formData.logo}
                      alt={formData.name || 'Team Logo'}
                      className="w-full h-full object-cover"
                    />
                  ) : (
                    <TeamOutlined className="text-neutral-400 text-xl" />
                  )}
                </div>
                {/* Logo Hover Overlay - Full circle */}
                <button
                  onClick={(e) => {
                    e.stopPropagation();
                    setShowLogoMenu(!showLogoMenu);
                  }}
                  className="absolute inset-0 bg-neutral-300/80 cursor-pointer rounded-full opacity-0 group-hover:opacity-100 transition-opacity flex items-center justify-center w-24 h-24"
                >
                  <CameraOutlined className="text-white text-lg" />
                </button>

                {/* Logo Menu Dropdown */}
                {showLogoMenu && (
                  <div className="absolute top-full left-0 mt-2 bg-white rounded-lg shadow-lg border border-neutral-200 py-2 min-w-[140px] z-10">
                    <button
                      onClick={(e) => {
                        e.stopPropagation();
                        triggerLogoUpload();
                      }}
                      className="w-full px-4 py-2 text-left text-sm text-neutral-700 hover:bg-neutral-50 flex items-center gap-2 cursor-pointer"
                    >
                      <UploadOutlined className="text-sm" />
                      {formData.logo ? 'Change Logo' : 'Upload Logo'}
                    </button>
                    {formData.logo && (
                      <button
                        onClick={(e) => {
                          e.stopPropagation();
                          handleRemoveLogo();
                        }}
                        className="w-full px-4 py-2 text-left text-sm text-red-600 hover:bg-red-50 flex items-center gap-2 cursor-pointer"
                      >
                        <DeleteOutlined className="text-sm" />
                        Remove Logo
                      </button>
                    )}
                  </div>
                )}
              </div>
            </div>

            {/* Team Name */}
            <div className="col-span-10 space-y-2">
              <label className="block text-sm font-medium text-neutral-700">
                Team Name <span className="text-danger-500">*</span>
              </label>
              <input
                type="text"
                className="w-full border border-neutral-200 rounded-lg px-3 py-2 text-sm focus:border-primary-500 focus:outline-none"
                placeholder="Enter team name"
                value={formData.name}
                onChange={(e) => handleInputChange('name', e.target.value)}
              />
              <p className="text-xs text-neutral-500">
                Click logo to upload or change team logo (circular format)
              </p>
            </div>
          </div>

          {/* Team Description */}
          <div className="space-y-2">
            <label className="block text-sm font-medium text-neutral-700">
              Description
            </label>
            <textarea
              className="w-full border border-neutral-200 rounded-lg px-3 py-2 text-sm focus:border-primary-500 focus:outline-none resize-none"
              placeholder="Enter team description (optional)"
              rows={3}
              value={formData.description || ''}
              onChange={(e) => handleInputChange('description', e.target.value)}
            />
          </div>

          {/* City */}
          <div className="space-y-2">
            <label className="block text-sm font-medium text-neutral-700">
              City <span className="text-danger-500">*</span>
            </label>
            <CityFilterSelect
              value={formData.city || 'all'}
              onChange={(city) =>
                handleInputChange('city', city === 'all' ? '' : city)
              }
              className="w-full"
              placeholder="Search cities..."
              allOptionLabel="Select a city"
              filterIcon={false}
            />
          </div>

          {/* Visibility */}
          <div className="space-y-2">
            <label className="block text-sm font-medium text-neutral-700">
              Team Visibility
            </label>
            <div className="flex gap-4">
              <label className="flex items-center gap-2 cursor-pointer">
                <input
                  type="radio"
                  name="visibility"
                  value="public"
                  checked={formData.visibility === 'public'}
                  onChange={(e) =>
                    handleInputChange('visibility', e.target.value as 'public')
                  }
                  className="text-primary-600"
                />
                <EyeOutlined className="text-info-600" />
                <span className="text-sm">Public</span>
              </label>
              <label className="flex items-center gap-2 cursor-pointer">
                <input
                  type="radio"
                  name="visibility"
                  value="private"
                  checked={formData.visibility === 'private'}
                  onChange={(e) =>
                    handleInputChange('visibility', e.target.value as 'private')
                  }
                  className="text-primary-600"
                />
                <EyeInvisibleOutlined className="text-neutral-600" />
                <span className="text-sm">Private</span>
              </label>
            </div>
          </div>

          {/* Team Information (Read-only for existing teams) */}
          {team && (
            <div className="grid grid-cols-2 gap-4">
              <div className="space-y-2">
                <label className="block text-sm font-medium text-neutral-700">
                  Members
                </label>
                <div className="flex items-center gap-2 p-3 bg-neutral-50 rounded-lg">
                  <UserOutlined className="text-neutral-500" />
                  <span className="text-sm text-neutral-700">
                    {team.member_count} member
                    {team.member_count !== 1 ? 's' : ''}
                  </span>
                </div>
              </div>

              <div className="space-y-2">
                <label className="block text-sm font-medium text-neutral-700">
                  Submission Status
                </label>
                <div className="flex items-center gap-2 p-3 bg-neutral-50 rounded-lg">
                  <div
                    className={cn(
                      'w-2 h-2 rounded-full',
                      team.has_submission ? 'bg-success-500' : 'bg-danger-500'
                    )}
                  />
                  <span
                    className={cn(
                      'text-sm font-medium',
                      team.has_submission
                        ? 'text-success-700'
                        : 'text-danger-700'
                    )}
                  >
                    {team.has_submission ? 'Submitted' : 'Not Submitted'}
                  </span>
                </div>
              </div>
            </div>
          )}

          {/* Tabs for Details and Members */}
          {team && (
            <div>
              <div className="flex border-b border-neutral-200">
                <button
                  className={cn(
                    'px-4 py-2 text-sm font-medium border-b-2 transition-colors cursor-pointer',
                    activeTab === 'details'
                      ? 'border-primary-500 text-primary-600'
                      : 'border-transparent text-neutral-500 hover:text-neutral-700'
                  )}
                  onClick={() => setActiveTab('details')}
                >
                  Team Details
                </button>
                <button
                  className={cn(
                    'px-4 py-2 text-sm font-medium border-b-2 transition-colors cursor-pointer',
                    activeTab === 'members'
                      ? 'border-primary-500 text-primary-600'
                      : 'border-transparent text-neutral-500 hover:text-neutral-700'
                  )}
                  onClick={() => setActiveTab('members')}
                >
                  Members ({team.member_count})
                </button>
              </div>

              <div className="pt-4">
                {activeTab === 'details' && (
                  <div className="space-y-4">
                    {/* Leader Information */}
                    {leader && (
                      <div className="space-y-2">
                        <label className="block text-sm font-medium text-neutral-700">
                          Team Leader
                        </label>
                        <div className="p-3 bg-neutral-50 rounded-lg">
                          <div className="flex items-center gap-3">
                            <div className="w-10 h-10 rounded-full bg-neutral-200 flex items-center justify-center overflow-hidden">
                              {leader.user.avatar ? (
                                <img
                                  src={leader.user.avatar}
                                  alt={leader.user.fullname}
                                  className="w-full h-full object-cover"
                                />
                              ) : (
                                <CrownOutlined className="text-yellow-600 text-sm" />
                              )}
                            </div>
                            <div>
                              <p className="text-sm font-medium text-neutral-900">
                                {leader.user.fullname}
                              </p>
                              <p className="text-xs text-neutral-500">
                                {leader.user.email}
                              </p>
                            </div>
                          </div>
                        </div>
                      </div>
                    )}

                    {/* Timestamps */}
                    <div className="grid grid-cols-2 gap-4">
                      <div className="space-y-2">
                        <label className="block text-sm font-medium text-neutral-700">
                          Created
                        </label>
                        <div className="flex items-center gap-2 p-3 bg-neutral-50 rounded-lg">
                          <CalendarOutlined className="text-neutral-500" />
                          <span className="text-sm text-neutral-700">
                            {new Date(team.created_at).toLocaleDateString(
                              'en-US',
                              {
                                year: 'numeric',
                                month: 'long',
                                day: 'numeric',
                                hour: '2-digit',
                                minute: '2-digit',
                              }
                            )}
                          </span>
                        </div>
                      </div>

                      <div className="space-y-2">
                        <label className="block text-sm font-medium text-neutral-700">
                          Last Updated
                        </label>
                        <div className="flex items-center gap-2 p-3 bg-neutral-50 rounded-lg">
                          <CalendarOutlined className="text-neutral-500" />
                          <span className="text-sm text-neutral-700">
                            {new Date(team.updated_at).toLocaleDateString(
                              'en-US',
                              {
                                year: 'numeric',
                                month: 'long',
                                day: 'numeric',
                                hour: '2-digit',
                                minute: '2-digit',
                              }
                            )}
                          </span>
                        </div>
                      </div>
                    </div>
                  </div>
                )}

                {activeTab === 'members' && (
                  <div className="space-y-4">
                    {/* Accepted Members */}
                    <div>
                      <h4 className="text-sm font-medium text-neutral-700 mb-3">
                        Active Members ({acceptedMembers.length})
                      </h4>
                      <div className="space-y-2">
                        {acceptedMembers.map((member) => (
                          <div
                            key={member.id}
                            className="flex items-center gap-3 p-3 bg-neutral-50 rounded-lg"
                          >
                            <div className="w-10 h-10 rounded-full bg-neutral-200 flex items-center justify-center overflow-hidden">
                              {member.user.avatar ? (
                                <img
                                  src={member.user.avatar}
                                  alt={member.user.fullname}
                                  className="w-full h-full object-cover"
                                />
                              ) : (
                                <UserOutlined className="text-neutral-500" />
                              )}
                            </div>
                            <div className="flex-1 min-w-0">
                              <div className="flex items-center gap-2">
                                <p className="text-sm font-medium text-neutral-900">
                                  {member.user.fullname}
                                </p>
                                {member.role === 'leader' && (
                                  <CrownOutlined className="text-yellow-600 text-xs" />
                                )}
                              </div>
                              <p className="text-xs text-neutral-500">
                                {member.user.email}
                              </p>
                              {member.user.skills.length > 0 && (
                                <div className="flex flex-wrap gap-1 mt-1">
                                  {member.user.skills
                                    .slice(0, 2)
                                    .map((skill, idx) => (
                                      <span
                                        key={idx}
                                        className="px-1 py-0.5 bg-primary-100 text-primary-700 text-xs rounded"
                                      >
                                        {skill}
                                      </span>
                                    ))}
                                  {member.user.skills.length > 2 && (
                                    <span className="text-xs text-neutral-400">
                                      +{member.user.skills.length - 2}
                                    </span>
                                  )}
                                </div>
                              )}
                            </div>
                            <div className="text-xs text-neutral-500">
                              Joined{' '}
                              {new Date(member.joined_at).toLocaleDateString()}
                            </div>
                          </div>
                        ))}
                      </div>
                    </div>

                    {/* Pending Members */}
                    {pendingMembers.length > 0 && (
                      <div>
                        <h4 className="text-sm font-medium text-neutral-700 mb-3">
                          Pending Members ({pendingMembers.length})
                        </h4>
                        <div className="space-y-2">
                          {pendingMembers.map((member) => (
                            <div
                              key={member.id}
                              className="flex items-center gap-3 p-3 bg-orange-50 border border-orange-200 rounded-lg"
                            >
                              <div className="w-10 h-10 rounded-full bg-neutral-200 flex items-center justify-center overflow-hidden">
                                {member.user.avatar ? (
                                  <img
                                    src={member.user.avatar}
                                    alt={member.user.fullname}
                                    className="w-full h-full object-cover"
                                  />
                                ) : (
                                  <UserOutlined className="text-neutral-500" />
                                )}
                              </div>
                              <div className="flex-1 min-w-0">
                                <div className="flex items-center gap-2">
                                  <p className="text-sm font-medium text-neutral-900">
                                    {member.user.fullname}
                                  </p>
                                  <ClockCircleOutlined className="text-orange-600 text-xs" />
                                </div>
                                <p className="text-xs text-neutral-500">
                                  {member.user.email}
                                </p>
                              </div>
                              <div className="flex gap-2">
                                <Button
                                  variant="primary"
                                  size="sm"
                                  className="flex items-center gap-1"
                                  onClick={() =>
                                    console.log('Accept member:', member.id)
                                  }
                                >
                                  <CheckCircleOutlined className="text-xs" />
                                  Accept
                                </Button>
                                <Button
                                  variant="secondary"
                                  size="sm"
                                  className="flex items-center gap-1"
                                  onClick={() =>
                                    console.log('Reject member:', member.id)
                                  }
                                >
                                  <CloseCircleOutlined className="text-xs" />
                                  Reject
                                </Button>
                              </div>
                            </div>
                          ))}
                        </div>
                      </div>
                    )}
                  </div>
                )}
              </div>
            </div>
          )}
        </div>

        {/* Footer */}
        <div className="flex items-center justify-between p-6 border-t border-neutral-200">
          <div>
            {team && (
              <Button
                variant="danger"
                size="md"
                onClick={() => setShowDeleteConfirm(true)}
                className="flex items-center gap-2"
              >
                <DeleteOutlined />
                Delete Team
              </Button>
            )}
          </div>

          <div className="flex items-center gap-3">
            <Button variant="secondary" size="md" onClick={onClose}>
              Cancel
            </Button>
            <Button
              variant="primary"
              size="md"
              onClick={handleSave}
              disabled={!canSave}
              className="flex items-center gap-2"
            >
              <SaveOutlined />
              {team ? 'Save Changes' : 'Create Team'}
            </Button>
          </div>
        </div>
      </div>

      {/* Delete Confirmation Modal */}
      {showDeleteConfirm && (
        <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-60 p-4">
          <div className="bg-white rounded-lg shadow-xl w-full max-w-md">
            <div className="p-6">
              <div className="flex items-center gap-4 mb-4">
                <div className="w-12 h-12 rounded-full bg-danger-100 flex items-center justify-center">
                  <ExclamationOutlined className="text-danger-600 text-xl" />
                </div>
                <div>
                  <h3 className="text-lg font-semibold text-neutral-900">
                    Delete Team
                  </h3>
                  <p className="text-sm text-neutral-500">
                    This action cannot be undone.
                  </p>
                </div>
              </div>

              <p className="text-sm text-neutral-700 mb-6">
                Are you sure you want to delete "{team?.name}"? This will
                permanently remove the team and all associated data.
              </p>

              <div className="flex items-center gap-3 justify-end">
                <Button
                  variant="secondary"
                  size="md"
                  onClick={() => setShowDeleteConfirm(false)}
                >
                  Cancel
                </Button>
                <Button
                  variant="danger"
                  size="md"
                  onClick={handleDelete}
                  className="flex items-center gap-2"
                >
                  <DeleteOutlined />
                  Delete Team
                </Button>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default ModalTeamDetail;
