/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SiteResourcesRouteImport } from './routes/_site/resources'
import { Route as SiteProfileRouteImport } from './routes/_site/profile'
import { Route as SiteMentoringRouteImport } from './routes/_site/mentoring'
import { Route as SiteArticlesRouteImport } from './routes/_site/articles'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard/index'
import { Route as SiteProfileIdRouteImport } from './routes/_site/profile_/$id'
import { Route as SiteMentoringIdRouteImport } from './routes/_site/mentoring_/$id'
import { Route as SiteArticlesSlugRouteImport } from './routes/_site/articles_/$slug'
import { Route as PublicAuthRegisterMentorRouteImport } from './routes/_public/auth/register-mentor'
import { Route as PublicAuthRegisterRouteImport } from './routes/_public/auth/register'
import { Route as PublicAuthLoginRouteImport } from './routes/_public/auth/login'
import { Route as PublicAuthGoogleOauthPopupRouteImport } from './routes/_public/auth/google-oauth-popup'
import { Route as PublicAuthGoogleCallbackRouteImport } from './routes/_public/auth/google-callback'
import { Route as PublicAuthForgotRouteImport } from './routes/_public/auth/forgot'
import { Route as AuthenticatedDashboardSettingsRouteImport } from './routes/_authenticated/dashboard_/settings'
import { Route as AuthenticatedDashboardRoadmapDiscoveryRouteImport } from './routes/_authenticated/dashboard/roadmap-discovery'
import { Route as AuthenticatedDashboardMentoringRouteImport } from './routes/_authenticated/dashboard/mentoring'
import { Route as AuthenticatedDashboardLearningPathRouteImport } from './routes/_authenticated/dashboard/learning-path'
import { Route as AuthenticatedDashboardFaqRouteImport } from './routes/_authenticated/dashboard/faq'
import { Route as AuthenticatedDashboardArticleBuilderRouteImport } from './routes/_authenticated/dashboard/article-builder'
import { Route as PublicAuthRegisterSuccessRouteImport } from './routes/_public/auth/register_/success'
import { Route as PublicAuthRegisterOtpRouteImport } from './routes/_public/auth/register_/otp'
import { Route as PublicAuthRegisterMentorSuccessRouteImport } from './routes/_public/auth/register-mentor_/success'
import { Route as PublicAuthRegisterMentorPendingRouteImport } from './routes/_public/auth/register-mentor_/pending'
import { Route as PublicAuthForgotSummonRouteImport } from './routes/_public/auth/forgot_/summon'
import { Route as PublicAuthForgotOtpRouteImport } from './routes/_public/auth/forgot_/otp'

const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteResourcesRoute = SiteResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => SiteRoute,
} as any)
const SiteProfileRoute = SiteProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SiteRoute,
} as any)
const SiteMentoringRoute = SiteMentoringRouteImport.update({
  id: '/mentoring',
  path: '/mentoring',
  getParentRoute: () => SiteRoute,
} as any)
const SiteArticlesRoute = SiteArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => SiteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const SiteProfileIdRoute = SiteProfileIdRouteImport.update({
  id: '/profile_/$id',
  path: '/profile/$id',
  getParentRoute: () => SiteRoute,
} as any)
const SiteMentoringIdRoute = SiteMentoringIdRouteImport.update({
  id: '/mentoring_/$id',
  path: '/mentoring/$id',
  getParentRoute: () => SiteRoute,
} as any)
const SiteArticlesSlugRoute = SiteArticlesSlugRouteImport.update({
  id: '/articles_/$slug',
  path: '/articles/$slug',
  getParentRoute: () => SiteRoute,
} as any)
const PublicAuthRegisterMentorRoute =
  PublicAuthRegisterMentorRouteImport.update({
    id: '/auth/register-mentor',
    path: '/auth/register-mentor',
    getParentRoute: () => PublicRoute,
  } as any)
const PublicAuthRegisterRoute = PublicAuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAuthLoginRoute = PublicAuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAuthGoogleOauthPopupRoute =
  PublicAuthGoogleOauthPopupRouteImport.update({
    id: '/auth/google-oauth-popup',
    path: '/auth/google-oauth-popup',
    getParentRoute: () => PublicRoute,
  } as any)
const PublicAuthGoogleCallbackRoute =
  PublicAuthGoogleCallbackRouteImport.update({
    id: '/auth/google-callback',
    path: '/auth/google-callback',
    getParentRoute: () => PublicRoute,
  } as any)
const PublicAuthForgotRoute = PublicAuthForgotRouteImport.update({
  id: '/auth/forgot',
  path: '/auth/forgot',
  getParentRoute: () => PublicRoute,
} as any)
const AuthenticatedDashboardSettingsRoute =
  AuthenticatedDashboardSettingsRouteImport.update({
    id: '/dashboard_/settings',
    path: '/dashboard/settings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoadmapDiscoveryRoute =
  AuthenticatedDashboardRoadmapDiscoveryRouteImport.update({
    id: '/roadmap-discovery',
    path: '/roadmap-discovery',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardMentoringRoute =
  AuthenticatedDashboardMentoringRouteImport.update({
    id: '/mentoring',
    path: '/mentoring',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardLearningPathRoute =
  AuthenticatedDashboardLearningPathRouteImport.update({
    id: '/learning-path',
    path: '/learning-path',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardFaqRoute =
  AuthenticatedDashboardFaqRouteImport.update({
    id: '/faq',
    path: '/faq',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardArticleBuilderRoute =
  AuthenticatedDashboardArticleBuilderRouteImport.update({
    id: '/article-builder',
    path: '/article-builder',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const PublicAuthRegisterSuccessRoute =
  PublicAuthRegisterSuccessRouteImport.update({
    id: '/auth/register_/success',
    path: '/auth/register/success',
    getParentRoute: () => PublicRoute,
  } as any)
const PublicAuthRegisterOtpRoute = PublicAuthRegisterOtpRouteImport.update({
  id: '/auth/register_/otp',
  path: '/auth/register/otp',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAuthRegisterMentorSuccessRoute =
  PublicAuthRegisterMentorSuccessRouteImport.update({
    id: '/auth/register-mentor_/success',
    path: '/auth/register-mentor/success',
    getParentRoute: () => PublicRoute,
  } as any)
const PublicAuthRegisterMentorPendingRoute =
  PublicAuthRegisterMentorPendingRouteImport.update({
    id: '/auth/register-mentor_/pending',
    path: '/auth/register-mentor/pending',
    getParentRoute: () => PublicRoute,
  } as any)
const PublicAuthForgotSummonRoute = PublicAuthForgotSummonRouteImport.update({
  id: '/auth/forgot_/summon',
  path: '/auth/forgot/summon',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAuthForgotOtpRoute = PublicAuthForgotOtpRouteImport.update({
  id: '/auth/forgot_/otp',
  path: '/auth/forgot/otp',
  getParentRoute: () => PublicRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/articles': typeof SiteArticlesRoute
  '/mentoring': typeof SiteMentoringRoute
  '/profile': typeof SiteProfileRoute
  '/resources': typeof SiteResourcesRoute
  '/dashboard/article-builder': typeof AuthenticatedDashboardArticleBuilderRoute
  '/dashboard/faq': typeof AuthenticatedDashboardFaqRoute
  '/dashboard/learning-path': typeof AuthenticatedDashboardLearningPathRoute
  '/dashboard/mentoring': typeof AuthenticatedDashboardMentoringRoute
  '/dashboard/roadmap-discovery': typeof AuthenticatedDashboardRoadmapDiscoveryRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/auth/forgot': typeof PublicAuthForgotRoute
  '/auth/google-callback': typeof PublicAuthGoogleCallbackRoute
  '/auth/google-oauth-popup': typeof PublicAuthGoogleOauthPopupRoute
  '/auth/login': typeof PublicAuthLoginRoute
  '/auth/register': typeof PublicAuthRegisterRoute
  '/auth/register-mentor': typeof PublicAuthRegisterMentorRoute
  '/articles/$slug': typeof SiteArticlesSlugRoute
  '/mentoring/$id': typeof SiteMentoringIdRoute
  '/profile/$id': typeof SiteProfileIdRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/auth/forgot/otp': typeof PublicAuthForgotOtpRoute
  '/auth/forgot/summon': typeof PublicAuthForgotSummonRoute
  '/auth/register-mentor/pending': typeof PublicAuthRegisterMentorPendingRoute
  '/auth/register-mentor/success': typeof PublicAuthRegisterMentorSuccessRoute
  '/auth/register/otp': typeof PublicAuthRegisterOtpRoute
  '/auth/register/success': typeof PublicAuthRegisterSuccessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/articles': typeof SiteArticlesRoute
  '/mentoring': typeof SiteMentoringRoute
  '/profile': typeof SiteProfileRoute
  '/resources': typeof SiteResourcesRoute
  '/dashboard/article-builder': typeof AuthenticatedDashboardArticleBuilderRoute
  '/dashboard/faq': typeof AuthenticatedDashboardFaqRoute
  '/dashboard/learning-path': typeof AuthenticatedDashboardLearningPathRoute
  '/dashboard/mentoring': typeof AuthenticatedDashboardMentoringRoute
  '/dashboard/roadmap-discovery': typeof AuthenticatedDashboardRoadmapDiscoveryRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/auth/forgot': typeof PublicAuthForgotRoute
  '/auth/google-callback': typeof PublicAuthGoogleCallbackRoute
  '/auth/google-oauth-popup': typeof PublicAuthGoogleOauthPopupRoute
  '/auth/login': typeof PublicAuthLoginRoute
  '/auth/register': typeof PublicAuthRegisterRoute
  '/auth/register-mentor': typeof PublicAuthRegisterMentorRoute
  '/articles/$slug': typeof SiteArticlesSlugRoute
  '/mentoring/$id': typeof SiteMentoringIdRoute
  '/profile/$id': typeof SiteProfileIdRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/auth/forgot/otp': typeof PublicAuthForgotOtpRoute
  '/auth/forgot/summon': typeof PublicAuthForgotSummonRoute
  '/auth/register-mentor/pending': typeof PublicAuthRegisterMentorPendingRoute
  '/auth/register-mentor/success': typeof PublicAuthRegisterMentorSuccessRoute
  '/auth/register/otp': typeof PublicAuthRegisterOtpRoute
  '/auth/register/success': typeof PublicAuthRegisterSuccessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_site': typeof SiteRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/_site/articles': typeof SiteArticlesRoute
  '/_site/mentoring': typeof SiteMentoringRoute
  '/_site/profile': typeof SiteProfileRoute
  '/_site/resources': typeof SiteResourcesRoute
  '/_authenticated/dashboard/article-builder': typeof AuthenticatedDashboardArticleBuilderRoute
  '/_authenticated/dashboard/faq': typeof AuthenticatedDashboardFaqRoute
  '/_authenticated/dashboard/learning-path': typeof AuthenticatedDashboardLearningPathRoute
  '/_authenticated/dashboard/mentoring': typeof AuthenticatedDashboardMentoringRoute
  '/_authenticated/dashboard/roadmap-discovery': typeof AuthenticatedDashboardRoadmapDiscoveryRoute
  '/_authenticated/dashboard_/settings': typeof AuthenticatedDashboardSettingsRoute
  '/_public/auth/forgot': typeof PublicAuthForgotRoute
  '/_public/auth/google-callback': typeof PublicAuthGoogleCallbackRoute
  '/_public/auth/google-oauth-popup': typeof PublicAuthGoogleOauthPopupRoute
  '/_public/auth/login': typeof PublicAuthLoginRoute
  '/_public/auth/register': typeof PublicAuthRegisterRoute
  '/_public/auth/register-mentor': typeof PublicAuthRegisterMentorRoute
  '/_site/articles_/$slug': typeof SiteArticlesSlugRoute
  '/_site/mentoring_/$id': typeof SiteMentoringIdRoute
  '/_site/profile_/$id': typeof SiteProfileIdRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_public/auth/forgot_/otp': typeof PublicAuthForgotOtpRoute
  '/_public/auth/forgot_/summon': typeof PublicAuthForgotSummonRoute
  '/_public/auth/register-mentor_/pending': typeof PublicAuthRegisterMentorPendingRoute
  '/_public/auth/register-mentor_/success': typeof PublicAuthRegisterMentorSuccessRoute
  '/_public/auth/register_/otp': typeof PublicAuthRegisterOtpRoute
  '/_public/auth/register_/success': typeof PublicAuthRegisterSuccessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/articles'
    | '/mentoring'
    | '/profile'
    | '/resources'
    | '/dashboard/article-builder'
    | '/dashboard/faq'
    | '/dashboard/learning-path'
    | '/dashboard/mentoring'
    | '/dashboard/roadmap-discovery'
    | '/dashboard/settings'
    | '/auth/forgot'
    | '/auth/google-callback'
    | '/auth/google-oauth-popup'
    | '/auth/login'
    | '/auth/register'
    | '/auth/register-mentor'
    | '/articles/$slug'
    | '/mentoring/$id'
    | '/profile/$id'
    | '/dashboard/'
    | '/auth/forgot/otp'
    | '/auth/forgot/summon'
    | '/auth/register-mentor/pending'
    | '/auth/register-mentor/success'
    | '/auth/register/otp'
    | '/auth/register/success'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/articles'
    | '/mentoring'
    | '/profile'
    | '/resources'
    | '/dashboard/article-builder'
    | '/dashboard/faq'
    | '/dashboard/learning-path'
    | '/dashboard/mentoring'
    | '/dashboard/roadmap-discovery'
    | '/dashboard/settings'
    | '/auth/forgot'
    | '/auth/google-callback'
    | '/auth/google-oauth-popup'
    | '/auth/login'
    | '/auth/register'
    | '/auth/register-mentor'
    | '/articles/$slug'
    | '/mentoring/$id'
    | '/profile/$id'
    | '/dashboard'
    | '/auth/forgot/otp'
    | '/auth/forgot/summon'
    | '/auth/register-mentor/pending'
    | '/auth/register-mentor/success'
    | '/auth/register/otp'
    | '/auth/register/success'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_public'
    | '/_site'
    | '/_authenticated/dashboard'
    | '/_site/articles'
    | '/_site/mentoring'
    | '/_site/profile'
    | '/_site/resources'
    | '/_authenticated/dashboard/article-builder'
    | '/_authenticated/dashboard/faq'
    | '/_authenticated/dashboard/learning-path'
    | '/_authenticated/dashboard/mentoring'
    | '/_authenticated/dashboard/roadmap-discovery'
    | '/_authenticated/dashboard_/settings'
    | '/_public/auth/forgot'
    | '/_public/auth/google-callback'
    | '/_public/auth/google-oauth-popup'
    | '/_public/auth/login'
    | '/_public/auth/register'
    | '/_public/auth/register-mentor'
    | '/_site/articles_/$slug'
    | '/_site/mentoring_/$id'
    | '/_site/profile_/$id'
    | '/_authenticated/dashboard/'
    | '/_public/auth/forgot_/otp'
    | '/_public/auth/forgot_/summon'
    | '/_public/auth/register-mentor_/pending'
    | '/_public/auth/register-mentor_/success'
    | '/_public/auth/register_/otp'
    | '/_public/auth/register_/success'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  SiteRoute: typeof SiteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/resources': {
      id: '/_site/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof SiteResourcesRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/profile': {
      id: '/_site/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof SiteProfileRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/mentoring': {
      id: '/_site/mentoring'
      path: '/mentoring'
      fullPath: '/mentoring'
      preLoaderRoute: typeof SiteMentoringRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/articles': {
      id: '/_site/articles'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof SiteArticlesRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_site/profile_/$id': {
      id: '/_site/profile_/$id'
      path: '/profile/$id'
      fullPath: '/profile/$id'
      preLoaderRoute: typeof SiteProfileIdRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/mentoring_/$id': {
      id: '/_site/mentoring_/$id'
      path: '/mentoring/$id'
      fullPath: '/mentoring/$id'
      preLoaderRoute: typeof SiteMentoringIdRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/articles_/$slug': {
      id: '/_site/articles_/$slug'
      path: '/articles/$slug'
      fullPath: '/articles/$slug'
      preLoaderRoute: typeof SiteArticlesSlugRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_public/auth/register-mentor': {
      id: '/_public/auth/register-mentor'
      path: '/auth/register-mentor'
      fullPath: '/auth/register-mentor'
      preLoaderRoute: typeof PublicAuthRegisterMentorRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/auth/register': {
      id: '/_public/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof PublicAuthRegisterRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/auth/login': {
      id: '/_public/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof PublicAuthLoginRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/auth/google-oauth-popup': {
      id: '/_public/auth/google-oauth-popup'
      path: '/auth/google-oauth-popup'
      fullPath: '/auth/google-oauth-popup'
      preLoaderRoute: typeof PublicAuthGoogleOauthPopupRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/auth/google-callback': {
      id: '/_public/auth/google-callback'
      path: '/auth/google-callback'
      fullPath: '/auth/google-callback'
      preLoaderRoute: typeof PublicAuthGoogleCallbackRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/auth/forgot': {
      id: '/_public/auth/forgot'
      path: '/auth/forgot'
      fullPath: '/auth/forgot'
      preLoaderRoute: typeof PublicAuthForgotRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_authenticated/dashboard_/settings': {
      id: '/_authenticated/dashboard_/settings'
      path: '/dashboard/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof AuthenticatedDashboardSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/roadmap-discovery': {
      id: '/_authenticated/dashboard/roadmap-discovery'
      path: '/roadmap-discovery'
      fullPath: '/dashboard/roadmap-discovery'
      preLoaderRoute: typeof AuthenticatedDashboardRoadmapDiscoveryRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/mentoring': {
      id: '/_authenticated/dashboard/mentoring'
      path: '/mentoring'
      fullPath: '/dashboard/mentoring'
      preLoaderRoute: typeof AuthenticatedDashboardMentoringRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/learning-path': {
      id: '/_authenticated/dashboard/learning-path'
      path: '/learning-path'
      fullPath: '/dashboard/learning-path'
      preLoaderRoute: typeof AuthenticatedDashboardLearningPathRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/faq': {
      id: '/_authenticated/dashboard/faq'
      path: '/faq'
      fullPath: '/dashboard/faq'
      preLoaderRoute: typeof AuthenticatedDashboardFaqRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/article-builder': {
      id: '/_authenticated/dashboard/article-builder'
      path: '/article-builder'
      fullPath: '/dashboard/article-builder'
      preLoaderRoute: typeof AuthenticatedDashboardArticleBuilderRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_public/auth/register_/success': {
      id: '/_public/auth/register_/success'
      path: '/auth/register/success'
      fullPath: '/auth/register/success'
      preLoaderRoute: typeof PublicAuthRegisterSuccessRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/auth/register_/otp': {
      id: '/_public/auth/register_/otp'
      path: '/auth/register/otp'
      fullPath: '/auth/register/otp'
      preLoaderRoute: typeof PublicAuthRegisterOtpRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/auth/register-mentor_/success': {
      id: '/_public/auth/register-mentor_/success'
      path: '/auth/register-mentor/success'
      fullPath: '/auth/register-mentor/success'
      preLoaderRoute: typeof PublicAuthRegisterMentorSuccessRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/auth/register-mentor_/pending': {
      id: '/_public/auth/register-mentor_/pending'
      path: '/auth/register-mentor/pending'
      fullPath: '/auth/register-mentor/pending'
      preLoaderRoute: typeof PublicAuthRegisterMentorPendingRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/auth/forgot_/summon': {
      id: '/_public/auth/forgot_/summon'
      path: '/auth/forgot/summon'
      fullPath: '/auth/forgot/summon'
      preLoaderRoute: typeof PublicAuthForgotSummonRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/auth/forgot_/otp': {
      id: '/_public/auth/forgot_/otp'
      path: '/auth/forgot/otp'
      fullPath: '/auth/forgot/otp'
      preLoaderRoute: typeof PublicAuthForgotOtpRouteImport
      parentRoute: typeof PublicRoute
    }
  }
}

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardArticleBuilderRoute: typeof AuthenticatedDashboardArticleBuilderRoute
  AuthenticatedDashboardFaqRoute: typeof AuthenticatedDashboardFaqRoute
  AuthenticatedDashboardLearningPathRoute: typeof AuthenticatedDashboardLearningPathRoute
  AuthenticatedDashboardMentoringRoute: typeof AuthenticatedDashboardMentoringRoute
  AuthenticatedDashboardRoadmapDiscoveryRoute: typeof AuthenticatedDashboardRoadmapDiscoveryRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardArticleBuilderRoute:
      AuthenticatedDashboardArticleBuilderRoute,
    AuthenticatedDashboardFaqRoute: AuthenticatedDashboardFaqRoute,
    AuthenticatedDashboardLearningPathRoute:
      AuthenticatedDashboardLearningPathRoute,
    AuthenticatedDashboardMentoringRoute: AuthenticatedDashboardMentoringRoute,
    AuthenticatedDashboardRoadmapDiscoveryRoute:
      AuthenticatedDashboardRoadmapDiscoveryRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
  AuthenticatedDashboardSettingsRoute: typeof AuthenticatedDashboardSettingsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
  AuthenticatedDashboardSettingsRoute: AuthenticatedDashboardSettingsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface PublicRouteChildren {
  PublicAuthForgotRoute: typeof PublicAuthForgotRoute
  PublicAuthGoogleCallbackRoute: typeof PublicAuthGoogleCallbackRoute
  PublicAuthGoogleOauthPopupRoute: typeof PublicAuthGoogleOauthPopupRoute
  PublicAuthLoginRoute: typeof PublicAuthLoginRoute
  PublicAuthRegisterRoute: typeof PublicAuthRegisterRoute
  PublicAuthRegisterMentorRoute: typeof PublicAuthRegisterMentorRoute
  PublicAuthForgotOtpRoute: typeof PublicAuthForgotOtpRoute
  PublicAuthForgotSummonRoute: typeof PublicAuthForgotSummonRoute
  PublicAuthRegisterMentorPendingRoute: typeof PublicAuthRegisterMentorPendingRoute
  PublicAuthRegisterMentorSuccessRoute: typeof PublicAuthRegisterMentorSuccessRoute
  PublicAuthRegisterOtpRoute: typeof PublicAuthRegisterOtpRoute
  PublicAuthRegisterSuccessRoute: typeof PublicAuthRegisterSuccessRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicAuthForgotRoute: PublicAuthForgotRoute,
  PublicAuthGoogleCallbackRoute: PublicAuthGoogleCallbackRoute,
  PublicAuthGoogleOauthPopupRoute: PublicAuthGoogleOauthPopupRoute,
  PublicAuthLoginRoute: PublicAuthLoginRoute,
  PublicAuthRegisterRoute: PublicAuthRegisterRoute,
  PublicAuthRegisterMentorRoute: PublicAuthRegisterMentorRoute,
  PublicAuthForgotOtpRoute: PublicAuthForgotOtpRoute,
  PublicAuthForgotSummonRoute: PublicAuthForgotSummonRoute,
  PublicAuthRegisterMentorPendingRoute: PublicAuthRegisterMentorPendingRoute,
  PublicAuthRegisterMentorSuccessRoute: PublicAuthRegisterMentorSuccessRoute,
  PublicAuthRegisterOtpRoute: PublicAuthRegisterOtpRoute,
  PublicAuthRegisterSuccessRoute: PublicAuthRegisterSuccessRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

interface SiteRouteChildren {
  SiteArticlesRoute: typeof SiteArticlesRoute
  SiteMentoringRoute: typeof SiteMentoringRoute
  SiteProfileRoute: typeof SiteProfileRoute
  SiteResourcesRoute: typeof SiteResourcesRoute
  SiteArticlesSlugRoute: typeof SiteArticlesSlugRoute
  SiteMentoringIdRoute: typeof SiteMentoringIdRoute
  SiteProfileIdRoute: typeof SiteProfileIdRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteArticlesRoute: SiteArticlesRoute,
  SiteMentoringRoute: SiteMentoringRoute,
  SiteProfileRoute: SiteProfileRoute,
  SiteResourcesRoute: SiteResourcesRoute,
  SiteArticlesSlugRoute: SiteArticlesSlugRoute,
  SiteMentoringIdRoute: SiteMentoringIdRoute,
  SiteProfileIdRoute: SiteProfileIdRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  SiteRoute: SiteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
