name: Test and Build

on:
  push:
    branches: ['develop']
  pull_request:
    branches: ['develop']

env:
  NODE_VERSION: 22.14.0
  CMS_SECRET: fake-secret
  CMS_POSTGRES_URL: postgres://user:password@localhost:5432/fake-db
  CMS_STORAGE_ENDPOINT: https://fake-s3-endpoint.com
  CMS_STORAGE_ACCESS_KEY_ID: fake-access-key
  CMS_STORAGE_SECRET_ACCESS_KEY: fake-secret-key
  CMS_STORAGE_REGION: ap-southeast-1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm install

      - name: Nx Build
        run: npx nx run-many --target=build --all
